---
title: Project Review Template 
author: Emma Hardin-Parker
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: All-cause Mortality Rates and Primary Care Physician Supply in US Counties 2021

Name of project author(s):Chaohua Li

Name of project reviewer: Emma Hardin-Parker


# Instructions


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation

### Feedback and Comments

The context of the project is strongly described. The mention of previous research coupled with highlighting gaps in current research, was strong and well explained. Appropriate references were used to call existing work into the introduction. The "why" behind this project was well understood and clear. 

### Summary assessment 

* strong contextualization and motivation


## Question description

### Feedback and Comments

The hypothesis was clear and was highly related to the data. I found no trouble understanding the "why" behind the project and could easily relate the question to the data. Since there are data from multiple sources, I would recommend having either a README.md document or some other form of documentation fully explaining the data to ensure that the subsequent hypotheses/analyses are fully clear and understandable. 

### Summary assessment

* question/hypotheses fully clear


## Data description


### Feedback and Comments

The data sources were provided, however, the data themselves were not fully explained. The README.md file within the raw-data folder is unrelated to the project. Given that there are multiple data sources, the data need to be fully explained. Codebooks were provided; however, it may be helpful to include an explanation of the complicated codebooks or relate them specifically to your project. The processingfile.qmd contains information on how the data were cleaned and processed; howevever it may be nice to include a more in-depth explanation of why certan variables were included or excluded and what the mindset was behind your decisions. 


### Summary assessment

* source and overall structure of data somewhat explained



## Data wrangling and exploratory analysis

### Feedback and Comments

As stated previously, the cleaning process should probably be explained more in-depth just so the reviewer or potential reproducer has a greater understanding of the "why." The codebook or explanation of variables was included in the supplementary-material.qmd, but it may be helpful to include this information either in a README.md file or some other place in the repo. You explain the code well, but more explanation may be needed. Exploratory and other modeling results are shown very well! 

### Summary assessment

* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis

### Feedback and Comments

The analysis methods were appropriate for the data and were performed properly. I would've liked to see more explanation within the analysis.qmd file. Regardless of whether the analysis were included in the "final" product (i.e. presented in the Manuscript) I found myself trying to explain the different analyses to myself. It may be good to over explain rather under explain. 

### Summary assessment

* defensible but not optimal analysis 


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results are presented very well. The tables and figures are both easy to read and understand. I appreciated your naming methods of plots and tables so it is easy for the reviewer to understand what exactly each plot/table is. 

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The study findings are well discussed and thorough. The overall conclusion and findings from this project were easy to understand. Strengths and limitations were fully explained. I would advise you to be more careful about wording. You mention that the multilevel linear model and random forest modeling techniques made findings robust; however, the results indicate that while PCP is negatively associated with all-cause mortality, it was not an important predictor in mortality rate. The techniques and processes may be robust, but the findings themselves may not be. I hope I am explaining this well! You have done a fantastic job with this project. 

### Summary assessment

* minor parts wrong, missing or unclear


# Overall project content evaluation

## Structure

### Feedback and Comments

The project is well-structured; however, the README.md file within the raw-data folder does not have any information concerning the .txt, .xlsx, .sas7bdat, or .csv files. Since the project contains a combination of many different data types and processed data, I think including a more in-depth README.md file would be helpful! Additionally, since you performed the data cleaning/merging within the processing-code folder and processing-code.qmd file, having a README.md file might be something to look into! I know you have comments and overall explanations throughout that document; however, it might be helpful to provide more context on the different data themselves for reproducibility sake. 

### Summary assessment
* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 

### Feedback and Comments

The project was very well documented. Each step of the analysis was clear and concise. I also appreciated the in-depth main README.md file. As stated previously, it may be helpful to include a README.md file for the analysis-code folder to provide additional information on the analysis process. Additionally, there were some explanations/interpretations under some of the model analyses, but it may be helpful to include some form of interpretation (no matter how menial) to each figure or model you fit! Overall, you did a great job of having a clear and concise documentation.  


### Summary assessment
* decently documented with some gaps



## Reproducibility

### Feedback and Comments

The results from this project were fully reproducible. As stated previously, I think it may be a good idea to ensure that all README.md files are thorough and explain any necessary processing or analysis in depth. I was also able to re-run the whole analysis without edits. 

### Summary assessment

* fully reproducible without issues


## Thoroughness

### Feedback and Comments

The overall study was very thorough. You mentioned in your limitations sections that more predictors should have been included so a variable selection process could have been conducted. I know hindsight is 20/20 and you may not need to go all the way back to perform this, but more explanation on why you chose the predictors you did and why only some "made the cut" would make your processing / analysis more robust! The "why" is SO important. The hypothesis was well answered and it was very clear what the overall goal was with this study. 


### Summary assessment

* strong level of thorougness


## Further comments

You did a great job with this project! I've added some suggestions/thoughts throughout different sections of this review. Please do not hesitate to reach out if you found any of my suggestions unclear! Great job again :) 




