---
title: Project Review 
author: Cora Hirst
date: 04-24-2024
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: "All-cause Mortality Rates and Primary Care Physician Supply in US Counties 2021"

Name of project author: Chaohua Li

Name of project reviewer: Cora Hirst


## Background, Context, and Motivation
How well is the context of the project described? Is a comprehensive background given, including summary of previous/related work? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The introduction was the perfect example of detailing what the outcome variable you will be assessing is, and each of the potential predictor variables that may contribute to it. You also outline the hyptohesis clearly and nicely at the end - that you will be assessing the strength of the negative association between primary care phsysician supply and all-cause mrotality. 

The motication for the prohect is clear in that it's postiion amongst previous work is identified. You have identified a gap in literature that you may be able to fill with the dataset you will describe below. 


### Summary Assessment
* strong contextualization and motivation


## Question Description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

The research question and hypothesis are totally clear and their association with the dataset is similarly made obvious. I also appreciate that you detail a bit of your approach at the end of your introduction - that the nested-nature of your dataset lends itself to multilevel / mixed linear models. 

### Summary Assessment
* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data presented is clear, but the structure with which it is presented is somewhat unclear. Making sure the hyperlinks to the sources work would be helfpul, and somehow subsetting, changing the font or color, or otherwise distinguishing the variables from the rest of the text would be a nice visual aid in interpreting the dataset. 


### Summary Assessment
* source and overall structure of data well explained


## Data Wrangling and Exploratory Analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The cleaning and processing process was detailed clearly in the manuscript, and further explored within the eda.qmd document. I appreciated the additional details in this document and think it would be advantageous to include these figures and discussions in the supplementary materials. 

Similary, I think the table for descriptive statistics could have been referenced in the manuscript but located in supplementary materials, as you don't typically refer to those statistics throughout the course of your analysis with frequency. 

### Summary Assessment
* essentially no weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The methods were appropriate for the data.  You include a few different models with clear interpretation of their results before running the analysis (setting expectations that will allow us to assess the sensitivity of the outcome to your predictor of choice.) 

I also appreciated that you utilized mutliple different models and assessed each of their performances, with a clear conclusion of which performed the best! 

### Summary Assessment
* strong and reasonable analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The figures were certainly the best figures you could have chosen to argue the statistical significance of your outcome. However, I do think they tend to get a little "messy" - for instance, figures 2 and 3 could benefit from changing the alpha level of your fill colors, so we can get a better sense of the overlap of the observation/prediction correlation between the training and test data. 

### Summary Assessment
* results are presented ok, with room for improvement


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The discussion section was succint and made clear reference to the initial hypothesis and study questions. Each of the models you used was discussed and the strengths and limitations (interpretability, performance, error, and in particular, the underlying model) were similarly acknowledged. I also appreciated that you detailed the limitations of cross sectional data, and not longitudinal data. The suggestions of different modeling approach (variable selection) with more variables was well-taken.

### Summary Assessment
* strong, complete and clear discussion


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments
Only relevant files were included and the order with which to run them was clear, even without reference to the readme files. Bravo!

All .qmd files were executable without problems. 

### Summary Assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The analysis.qmd file was clear and concisely documented, so that I understood what each section and each line hoped to accomplish. I wish a bit more of the logic behind your processing was explained in the processing file itself, as throughouly as it was in the manuscrip. 

### Summary Assessment
* fully and well documented


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

I did not run into any problems reproducing your analysis or processing code once I made a slight edit to line 211 to extract the RMSE from the correct object. 

### Summary assessment
* small parts not reproducible or required manual intervention


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Refer back to my assessment of your conclusion! I appreciated that you acknowledged that feature selection on a dataset with a greater number of predictors may have helped to assess the relative contribution of PCP supply to the outcome to a greater extent than your models. However, it was nice to see that you acknowedged that both models converged on the same conclusion, which adds weight to your interpretation!

### Summary Assessment
* strong level of thoroughness


## Further Comments

I am impressed with the throughouness with which you assessed the performance of your models!

