---
title: "All-cause Mortality Rates and Primary Care Physician Supply in US Counties 2021"
subtitle: ""
author: Chaohua Li
date: "`r Sys.Date()`"
format:
  docx:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: ../../assets/mada.bib
csl: ../../assets/apa.csl
---

```{r, echo=FALSE, message=FALSE}
# load a few R packages
library(here)
library(knitr)
```

# Part 1

# Summary/Abstract

In this project, I will conduct a cross-sectional study on the county level and examine the potential association between age-adjusted all-cause mortality rate and primary care physician supply for US counties. A multilevel linear model will be used, and multiple potential confounders will be accounted for in the model.

{{< pagebreak >}}

# Introduction

## General Background Information

The all-cause mortality rate is an important indicator of general population health. Although the age-adjusted all-cause mortality rate consistently declined in the US from 1935 to 2014, a notable increasing trend after 2015 has been observed [@woolf_new_2023]. Personal level access to primary care is highly associated with mortality, morbidity, and healthcare costs [@peart_patient_2018]. There is a need to study how primary care physician supply on the geographic levels is associated with all-cause mortality rates in the US.

## Description of data and data source

Three data sources will be used for this study. (1) Multiple Cause of Death File of 2021 from CDC WONDER (https://wonder.cdc.gov/mcd.html). I will obtain county-level age-adjusted all-cause mortality rates (deaths/100k people) from this source. (2) Area Health Resource File of 2021 from U.S. Department of Health & Human Services (https://data.hrsa.gov/data/download). I will obtain county-level primary care physician supply (physicians/100k people) and rural/urban categorization of the county from this file. (3) estimates of 2021 from 2017-2021 5-year American Community Survey (https://www.nhgis.org/). I will obtain states, regions, and some county-level socioeconomic measures as potential confounders for modeling. These measures may include %Living under poverty line, %Without a high school diploma, %Hispanic, %NH-Black, %Unemployed, %Without health insurance, and so on.

Data from the three sources will be merged by using the FIPS code which serves as the ID for counties.

## Questions/Hypotheses to be addressed

My hypothesis is that primary care physician supply is negatively associated with age-adjusted all-cause mortality rate among US counties.Since counties can be considered nested within states or regions, a multilevel linear model will be used. The dependent variable will be mortality rate, main predictor will be primary care physician supply, and the socioeconomic measures will be the covariates in the model.

{{< pagebreak >}}

# Methods

*Describe your methods. That should describe the data, the cleaning processes, and the analysis approaches. You might want to provide a shorter description here and all the details in the supplement.*

## Schematic of workflow

## Data aquisition

*As applicable, explain where and how you got the data. If you directly import the data from an online source, you can combine this section with the next.*

## Data import and cleaning

*Write code that reads in the file and cleans it so it's ready for analysis. Since this will be fairly long code for most datasets, it might be a good idea to have it in one or several R scripts. If that is the case, explain here briefly what kind of cleaning/processing you do, and provide more details and well documented code somewhere (e.g. as supplement in a paper). All materials, including files that contain code, should be commented well so everyone can follow along.*

## Statistical analysis

*Explain anything related to your statistical analyses.*

{{< pagebreak >}}

# Results

## Exploratory/Descriptive analysis

*Use a combination of text/tables/figures to explore and describe your data. Show the most important descriptive results here. Additional ones should go in the supplement. Even more can be in the R and Quarto files that are part of your project.*

## Basic statistical analysis

*To get some further insight into your data, if reasonable you could compute simple statistics (e.g. simple models with 1 predictor) to look for associations between your outcome(s) and each individual predictor variable. Though note that unless you pre-specified the outcome and main exposure, any "p\<0.05 means statistical significance" interpretation is not valid.*

## Full analysis

*Use one or several suitable statistical/machine learning methods to analyze your data and to produce meaningful figures, tables, etc. This might again be code that is best placed in one or several separate R scripts that need to be well documented. You want the code to produce figures and data ready for display as tables, and save those. Then you load them here.*

{{< pagebreak >}}

# Discussion

## Summary and Interpretation

*Summarize what you did, what you found and what it means.*

## Strengths and Limitations

*Discuss what you perceive as strengths and limitations of your analysis.*

## Conclusions

*What are the main take-home messages?*

*Include citations in your Rmd file using bibtex, the list of references will automatically be placed at the end*

This paper [@leek2015] discusses types of analyses.

These papers [@mckay2020; @mckay2020a] are good examples of papers published using a fully reproducible setup similar to the one shown in this template.

Note that this cited reference will show up at the end of the document, the reference formatting is determined by the CSL file specified in the YAML header. Many more style files for almost any journal [are available](https://www.zotero.org/styles). You also specify the location of your bibtex reference file in the YAML. You can call your reference file anything you like, I just used the generic word `references.bib` but giving it a more descriptive name is probably better.

{{< pagebreak >}}

# References
